name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.16.x"

      - name: Build Tests
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_MAIN=OFF -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=OFF
          make simple-tad-tests

      - name: Test
        run: |
          ./simple-tad-tests